### ISSUE TITLE
Receiving no workload

### ISSUE THREAD

**Issue by elouet** [lichess-org/fishnet#223]
I am running fishnet on a x86 cloud instance without any issue.
I have installed it from source on an idle arm Linux box. The build was successful, and the client runs, but never receives any job to process, it seems : 

```
#   _________         .    .
#  (..       \_    ,  |\  /|
#   \       O  \  /|  \ \/ /
#    \______    \/ |   \  /      _____ _     _     _   _      _
#       vvvv\    \ |   /  |     |  ___(_)___| |__ | \ | | ___| |_
#       \^^^^  ==   \_/   |     | |_  | / __| '_ \|  \| |/ _ \ __|
#        `\_   ===    \.  |     |  _| | \__ \ | | | |\  |  __/ |_
#        / /\_   \ /      |     |_|   |_|___/_| |_|_| \_|\___|\__| 2.5.2-dev
#        |/   \_  \|      /
#               \________/      Distributed Stockfish analysis for lichess.org

### Checking configuration ...

Endpoint: https://lichess.org/fishnet
Backlog: Join queue if user backlog >= 30s or system backlog >= 3600s
CPU features: (empty)
Engine: stockfish-armv8 (for GPLv3, run: target/release/fishnet license)
Cores: 2

### Running (CTRL-C to stop) ...

Recording to new stats file ~/.fishnet-stats ...
Going idle for 115s.
Going idle for 114s.
><> fishnet/2.5.2-dev: 800 knps??? (nnue), 0 batches, 0 positions, 0 total nodes

```

A I doing something wrong ?

**Comment by niklasf** [comment]
Hi, thanks for running fishnet! This question comes up from time to time, so I have now added it to the FAQ: https://github.com/lichess-org/fishnet#why-does-my-client-remain-idle

In this case, it looks like your client is configured to stay idle unless a backlog is building up. You can rerun the configuration dialog with something like `./fishnet-x86_64-unknown-linux-gnu configure`.
