### ISSUE TITLE
Create OpenShift/K8s Deployment for FishNet

### ISSUE THREAD

**Issue by toughIQ** [lichess-org/fishnet#235]
I would suggest to adapt/enhance the container image itself and the way to deploy it, so it can be run on a current and secure OCP/K8s Cluster.

What would have to be done:

1. run or work without `root` privileges
2. change `~/.fishnet-stats` permissions
3. create a `Deployment` instead of a `Pod` so scaling could be possible.

I am currently looking into these topics, but wanted to discuss, if there are any further ideas regarding this.

Thanks, Chris

**Comment by niklasf** [comment]
Sounds good. The client definitely doesn't need root privileges at runtime, so changing the container should work.

**Comment by toughIQ** [comment]
I just created a pull request for the file permissions.
I am currently working on the OpenShift documentation. Since I dont have a native K8s environment at hand, the documentation is written and tested against OCP4.

**Comment by toughIQ** [comment]
I just updated the deployment.yaml file to use the now official multiarch fishnet image

**Comment by niklasf** [comment]
Merged #238.
