### ISSUE TITLE
support SF armv8-dotprod arch

### ISSUE THREAD

**Issue by darkBuddha** [lichess-org/fishnet#248]
Hi,

on Ampere Altra CPUs (Arm v8.2+), SF 16 `armv8-dotprod` builds consistently run ~9% faster as `armv8`:

**armv8**
```
Total time (ms) : 2694
Nodes searched  : 2593605
Nodes/second    : 962733
```

**armv8-dotprod**
```
Total time (ms) : 2939
Nodes searched  : 2593605
Nodes/second    : 882478
```

I have no idea how to detect the availability, `CARGO_CFG_TARGET_FEATURE` doesn't know about it, it shows only `neon`. Maybe it could be enabled manually via flag. Just wanted to share this finding, roughly 10% is not bad.

**Comment by niklasf** [comment]
Makes sense.

`CARGO_CFG_TARGET_FEATURE` only has it if it was specifically selected, or with `-C target-cpu=native`. Runtime detection with https://doc.rust-lang.org/stable/std/arch/macro.is_aarch64_feature_detected.html also works.

Will be included in the next release.
