### ISSUE TITLE
Local Lichess "Request a Computer Analysis"?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [lichess-org/fishnet#249]
`fishnet` is for donating compute to Lichess, if I understand correctly. Does it also support a fully local execution of Lichess's `Request a Computer Analysis` feature? If not, I'd appreciate pointers on where I could find something similar, paid or not (I understand it's off topic and don't mind Issue closure). I'd also suggest it'd be very helpful for Lichess to make this possible.

**Comment by OverLordGoldDragon** [comment]
Thanks, though that's Leela-oriented.

Lichess could also keep stuff in the browser and simply allow using local hardware. I'm particularly after the accuracy plot, that's currently made very quickly and is probably very suboptimal.

**Comment by OverLordGoldDragon** [comment]
https://github.com/rooklift/nibbler/issues/234

**Comment by obj-obj** [comment]
> Thanks, though that's Leela-oriented.
> 
> Lichess could also keep stuff in the browser and simply allow using local hardware. I'm particularly after the accuracy plot, that's currently made very quickly and is probably very suboptimal.

True, both Stockfish and Rust can be compiled to webassembly

**Comment by OverLordGoldDragon** [comment]
FWIW there's now https://github.com/rooklift/nibbler/pull/237 , but it'd be nicer to have the full Lichess interface

**Comment by niklasf** [comment]
As for fishnet, with [`--endpoint`](https://github.com/lichess-org/lila/wiki/Lichess-Development-Onboarding#optional-setup-stockfish-analysis) and the [protocol](https://github.com/lichess-org/fishnet/blob/master/doc/protocol.md) it can be used as a building block to do this, but nothing more.
