### ISSUE TITLE
Set niceness value

### ISSUE THREAD

**Issue by obj-obj** [lichess-org/fishnet#251]
Niceness on Linux sets CPU priority. Self-setting the niceness to 19 (the maximum) would put fishnet at low priority compared to all other processes, which is useful for running fishnet on desktop systems. I'm currently running fishnet using all my cores at a niceness value of 19, and the system is almost as responsive as if it wasn't at 100% CPU usage.

Maybe [this crate](https://lib.rs/crates/thread-priority) could be used?.

**Comment by niklasf** [comment]
This now landed in [fishnet v2.8.1](https://github.com/lichess-org/fishnet/releases/tag/v2.8.1).
