### ISSUE TITLE
very slow nodes is it paranoya or incompetence? 

### ISSUE THREAD

**Issue by Parakovsky** [lichess-org/fishnet#261]
*cross post in discord for discussion*

so i try to use my laptop as a node but sometimes the 40 games analysis will take 40 minutes and i can't analyze anything else during that time, not in the way i wanted it too. so my question is is there some kind of not subtle sabotage by competitor famous site going on where they provide some kind of very slow 1kbps nodes in mass quantity to make analysis unusable or is it just some peers technicaly incompetent and try to rent too low of a power? in any event, this sucks!

**Comment by niklasf** [comment]
Responded in Discord.
