### ISSUE TITLE
Windoes exe exits abruptly during Configuration prompt

### ISSUE THREAD

**Issue by haisu2** [lichess-org/fishnet#270]
On v2.9.4 in the configuration prompt that pops up by clicking on fishnet in the Windows file explorer, the terminal window closes abruptly at the last step if the user types "no" then presses Enter when prompted by "Done. Write configuration to "fishnet.ini" now? (default: yes)"
I think the expected behavior should be for fishnet to run with the entered fishnet key, number of logical cores and client idleness without writing a fishnet.ini config file. Otherwise, there is no point to ask the last question before fishnet runs.

**Comment by niklasf** [comment]
Good idea! Implemented.
